// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzxolsqpaugfpuaxvqmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6eG9sc3FwYXVnZnB1YXh2cW1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NTU3NzUsImV4cCI6MjA2NjAzMTc3NX0.9Rb9EXdXic7YP-JIxzCMfQTYjZySWfObMLcS1BGq4ck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);